=== essenius/FitNesseFitSharpSupportFunctions/SupportFunctionsTest/TestData.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="items">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="DimensionGridlineInterval">
          <xs:complexType>
            <xs:attribute name="range" type="xs:double" use="required" />
            <xs:attribute name="interval" type="xs:float" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="ExtensionFunctionInferType">
          <xs:complexType>
            <xs:attribute name="testcase" type="xs:string" use="required" />
            <xs:attribute name="value1" type="xs:string" use="required" />
            <xs:attribute name="value2" type="xs:string" use="required" />
            <xs:attribute name="expectedType" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="MeasurementCompare">
          <xs:complexType>
            <xs:attribute name="testcase" type="xs:string" use="required" />
            <xs:attribute name="tolerance" type="xs:string" use="required" />
            <xs:attribute name="compareType" type="xs:string" use="optional" />
            <xs:attribute name="expectedTimestamp" type="xs:dateTime" use="optional" />
            <xs:attribute name="expectedValue" type="xs:string" use="optional" />
            <xs:attribute name="expectedIsGood" type="xs:boolean" use="optional" />
            <xs:attribute name="actualTimestamp" type="xs:dateTime" use="optional" />
            <xs:attribute name="actualValue" type="xs:string" use="optional" />
            <xs:attribute name="actualIsGood" type="xs:boolean" use="optional" />
            <xs:attribute name="issue" type="xs:string" use="required" />
            <xs:attribute name="resultTimeStamp" type="xs:dateTime" use="required" />
            <xs:attribute name="resultExpectedValue" type="xs:string" use="optional" />
            <xs:attribute name="resultExpectedIsGood" type="xs:boolean" use="optional" />
            <xs:attribute name="resultActualValue" type="xs:string" use="optional" />
            <xs:attribute name="resultActualIsGood" type="xs:boolean" use="optional" />
            <xs:attribute name="resultDelta" type="xs:decimal" use="optional" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="TimeSeriesComparisonDoTable">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="data">
                <xs:complexType>
                  <xs:attribute name="timestamp" type="xs:dateTime" use="required" />
                  <xs:attribute name="exists" type="xs:string" use="required" />
                  <xs:attribute name="expectedValue" type="xs:string" use="optional" />
                  <xs:attribute name="actualValue" type="xs:string" use="optional" />
                  <xs:attribute name="pass" type="xs:string" use="required" />
                  <xs:attribute name="value" type="xs:string" use="optional" />
                  <xs:attribute name="delta" type="xs:string" use="optional" />
                  <xs:attribute name="deltaPercentage" type="xs:string" use="optional" />
                  <xs:attribute name="timestampOut" type="xs:string" use="optional" />
                  <xs:attribute name="expectedIsGood" type="xs:string" use="optional" />
                  <xs:attribute name="actualIsGood" type="xs:string" use="optional" />
                  <xs:attribute name="isGood" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="testcase" type="xs:string" use="required" />
            <xs:attribute name="tolerance" type="xs:string" use="optional" />
            <xs:attribute name="usedTolerance" type="xs:string" use="optional" />
            <xs:attribute name="displayTolerance" type="xs:string" use="optional" />
            <xs:attribute name="isGood" type="xs:string" use="required" />
            <xs:attribute name="failures" type="xs:unsignedByte" use="required" />
            <xs:attribute name="datapoints" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="TimeSeriesDataRange">
          <xs:complexType>
            <xs:attribute name="testcase" type="xs:string" use="required" />
            <xs:attribute name="count" type="xs:unsignedByte" use="required" />
            <xs:attribute name="lowValue" type="xs:string" use="optional" />
            <xs:attribute name="highValue" type="xs:string" use="optional" />
            <xs:attribute name="expectedRange" type="xs:double" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="TimeSeriesDataType">
          <xs:complexType>
            <xs:attribute name="testcase" type="xs:string" use="required" />
            <xs:attribute name="count" type="xs:unsignedShort" use="required" />
            <xs:attribute name="value1" type="xs:string" use="required" />
            <xs:attribute name="value2" type="xs:string" use="required" />
            <xs:attribute name="expectedType" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="Tolerance">
          <xs:complexType>
            <xs:attribute name="testcase" type="xs:string" use="required" />
            <xs:attribute name="range" type="xs:string" use="required" />
            <xs:attribute name="tolerance" type="xs:string" use="required" />
            <xs:attribute name="expectedValue" type="xs:decimal" use="required" />
            <xs:attribute name="expectedPrecision" type="xs:string" use="required" />
            <xs:attribute name="expectedRendering" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="ToleranceValue">
          <xs:complexType>
            <xs:attribute name="testcase" type="xs:string" use="required" />
            <xs:attribute name="range" type="xs:string" use="required" />
            <xs:attribute name="tolerance" type="xs:string" use="required" />
            <xs:attribute name="expectedOutput" type="xs:double" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="ValueCompare">
          <xs:complexType>
            <xs:attribute name="testcase" type="xs:string" use="required" />
            <xs:attribute name="tolerance" type="xs:string" use="optional" />
            <xs:attribute name="compareType" type="xs:string" use="optional" />
            <xs:attribute name="expected" type="xs:string" use="optional" />
            <xs:attribute name="actual" type="xs:string" use="optional" />
            <xs:attribute name="issue" type="xs:string" use="required" />
            <xs:attribute name="resultExpected" type="xs:string" use="optional" />
            <xs:attribute name="resultActual" type="xs:string" use="optional" />
            <xs:attribute name="resultDelta" type="xs:decimal" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== essenius/FitNesseFitSharpSupportFunctions/SupportFunctions/SupportFunctionsTest/TestData.xml
<?xml version="1.0" encoding="utf-8"?>

<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation='TestData.xsd'>
  <DimensionGridlineInterval range="0.02" interval="0.002" />
  <DimensionGridlineInterval range="0.03" interval="0.005" />
  <DimensionGridlineInterval range="0.004" interval="0.0005" />
  <DimensionGridlineInterval range="0.07" interval="0.01" />
  <DimensionGridlineInterval range="0.09" interval="0.01" />
  <DimensionGridlineInterval range="0.1" interval="0.01" />
  <DimensionGridlineInterval range="0.11" interval="0.02 " />
  <DimensionGridlineInterval range="5" interval="0.5" />
  <DimensionGridlineInterval range="235" interval="25" />
  <DimensionGridlineInterval range="357" interval="50" />
  <DimensionGridlineInterval range="798" interval="100" />
  <DimensionGridlineInterval range="1366" interval="200" />
  <DimensionGridlineInterval range="123456789" interval="20000000" />
  <DimensionGridlineInterval range="1.23456789e+30" interval="2e+29" />
  <DimensionGridlineInterval range="2.23456789e-30" interval="2.5e-31" />

  <ExtensionFunctionInferType testcase="Double-Int" value1="12.5" value2="13" expectedType="System.Double" />
  <ExtensionFunctionInferType testcase="Double-Bool" value1="12.5" value2="true" expectedType="System.String" />
  <ExtensionFunctionInferType testcase="Double-Long" value1="1e15" value2="2147483648" expectedType="System.Double" />
  <ExtensionFunctionInferType testcase="Double-String" value1="12.5" value2="Hi1" expectedType="System.String" />
  <ExtensionFunctionInferType testcase="Double-Double" value1="12.5" value2="13.2" expectedType="System.Double" />
  <ExtensionFunctionInferType testcase="Int-Long" value1="12" value2="2147483648" expectedType="System.Int64" />
  <ExtensionFunctionInferType testcase="Int-Double" value1="12" value2="12.1" expectedType="System.Double" />
  <ExtensionFunctionInferType testcase="Int-Bool" value1="12" value2="True" expectedType="System.String" />
  <ExtensionFunctionInferType testcase="Int-String" value1="12" value2="Hi1" expectedType="System.String" />
  <ExtensionFunctionInferType testcase="Int-Int" value1="12" value2="13" expectedType="System.Int32" />
  <ExtensionFunctionInferType testcase="Long-Int" value1="2147483648" value2="12" expectedType="System.Int64" />
  <ExtensionFunctionInferType testcase="Long-Long" value1="2147483648" value2="2147483648" expectedType="System.Int64" />
  <ExtensionFunctionInferType testcase="Long-Double" value1="2147483648" value2="12.5" expectedType="System.Double" />
  <ExtensionFunctionInferType testcase="Long-Bool" value1="2147483648" value2="False" expectedType="System.String" />
  <ExtensionFunctionInferType testcase="Long-String" value1="2147483648" value2="Hi1" expectedType="System.String" />
  <ExtensionFunctionInferType testcase="Bool-String" value1="False" value2="Hi1" expectedType="System.String" />
  <ExtensionFunctionInferType testcase="Bool-Bool" value1="False" value2="True" expectedType="System.Boolean" />
  <ExtensionFunctionInferType testcase="Bool-Double" value1="False" value2="12.5" expectedType="System.String" />
  <ExtensionFunctionInferType testcase="String-Double" value1="Hi1" value2="1e10" expectedType="System.String" />
  <ExtensionFunctionInferType testcase="Double-InfT-NaN" value1="Infinity" value2="NaN" expectedType="System.Double" />
  <ExtensionFunctionInferType testcase="Double-InfS-NaN" value1="∞" value2="NaN" expectedType="System.Double" />

  <MeasurementCompare testcase="0-All Good String" tolerance="0" compareType="System.String"
                      expectedTimestamp="2016-12-24T00:14:00.0000000" expectedValue="Hi1" expectedIsGood="true"
                      actualTimestamp="2016-12-24T00:14:00.0000000" actualValue="Hi1" actualIsGood="true"
                      issue="None" resultTimeStamp="2016-12-24T00:14:00.0000000"
                      resultExpectedValue="Hi1" resultExpectedIsGood="true" resultActualValue="Hi1"
                      resultActualIsGood="true" />
  <MeasurementCompare testcase="1-All Good Int" tolerance="0" compareType="System.Int32"
                      expectedTimestamp="2016-12-24T00:15:00.0000000" expectedValue="12345" expectedIsGood="true"
                      actualTimestamp="2016-12-24T00:15:00.0000000" actualValue="12345" actualIsGood="true"
                      issue="None" resultTimeStamp="2016-12-24T00:15:00.0000000"
                      resultExpectedValue="12345" resultExpectedIsGood="true" resultActualValue="12345"
                      resultActualIsGood="true" />
  <MeasurementCompare testcase="2-All Good Double" tolerance="0.001" compareType="System.Double"
                      expectedTimestamp="2016-12-24T00:16:00.0000000" expectedValue="12.1" expectedIsGood="true"
                      actualTimestamp="2016-12-24T00:16:00.0000000" actualValue="12.1" actualIsGood="true"
                      issue="None" resultTimeStamp="2016-12-24T00:16:00.0000000"
                      resultExpectedValue="12.1" resultExpectedIsGood="true" resultActualValue="12.1"
                      resultActualIsGood="true" />
  <MeasurementCompare testcase="3-Type Mismatch" tolerance="0"
                      expectedTimestamp="2016-12-24T00:17:00.0000000" expectedValue="12.1" expectedIsGood="true"
                      actualTimestamp="2016-12-24T00:17:00.0000000" actualValue="Hi1" actualIsGood="true"
                      issue="ValueIssue" resultTimeStamp="2016-12-24T00:17:00.0000000"
                      resultExpectedValue="12.1" resultExpectedIsGood="true" resultActualValue="Hi1"
                      resultActualIsGood="true" />
  <MeasurementCompare testcase="4-Double Mismatch" tolerance="0.001:4"
                      expectedTimestamp="2016-12-24T00:19:00.0000000" expectedValue="12.0" expectedIsGood="true"
                      actualTimestamp="2016-12-24T00:19:00.0000000" actualValue="12.01" actualIsGood="true"
                      issue="OutsideToleranceIssue" resultTimeStamp="2016-12-24T00:19:00.0000000" resultDelta="0.01"
                      resultExpectedValue="12" resultExpectedIsGood="true" resultActualValue="12.01"
                      resultActualIsGood="true" />
  <MeasurementCompare testcase="5-Double Mismatch With 5 Significant Digits" tolerance="0.0012345678:5"
                      expectedTimestamp="2016-12-24T00:19:00.0000000" expectedValue="12.00345678901"
                      expectedIsGood="true"
                      actualTimestamp="2016-12-24T00:19:00.0000000" actualValue="12.00567890123" actualIsGood="true"
                      issue="OutsideToleranceIssue" resultTimeStamp="2016-12-24T00:19:00.0000000"
                      resultExpectedValue="12.0034568" resultActualValue="12.0056789" resultDelta="0.0022221"
                      resultExpectedIsGood="true" resultActualIsGood="true" />
  <MeasurementCompare testcase="6-Double NaN" tolerance="0.0012345678:5"
                      expectedTimestamp="2016-12-24T00:19:00.0000000" expectedValue="NaN" expectedIsGood="true"
                      actualTimestamp="2016-12-24T00:19:00.0000000" actualValue="NaN" actualIsGood="true"
                      issue="None" resultTimeStamp="2016-12-24T00:19:00.0000000"
                      resultExpectedValue="NaN" resultActualValue="NaN" resultExpectedIsGood="true"
                      resultActualIsGood="true" />
  <MeasurementCompare testcase="7-Long Mismatch" tolerance="1"
                      expectedTimestamp="2016-12-24T00:20:00.0000000" expectedValue="636188256000010001"
                      expectedIsGood="true"
                      actualTimestamp="2016-12-24T00:20:00.0000000" actualValue="636188256000010000"
                      actualIsGood="true"
                      issue="WithinTolerance" resultTimeStamp="2016-12-24T00:20:00.0000000"
                      resultExpectedValue="636188256000010001" resultActualValue="636188256000010000"
                      resultExpectedIsGood="true" resultActualIsGood="true" />
  <MeasurementCompare testcase="8-Int Mismatch" tolerance="0"
                      expectedTimestamp="2016-12-24T00:20:00.0000000" expectedValue="11" expectedIsGood="true"
                      actualTimestamp="2016-12-24T00:20:00.0000000" actualValue="12" actualIsGood="true"
                      issue="ValueIssue" resultTimeStamp="2016-12-24T00:20:00.0000000"
                      resultExpectedValue="11" resultActualValue="12" resultExpectedIsGood="true"
                      resultActualIsGood="true" />
  <MeasurementCompare testcase="9-Bool Mismatch" tolerance="0"
                      expectedTimestamp="2016-12-24T00:20:00.0000000" expectedValue="True" expectedIsGood="true"
                      actualTimestamp="2016-12-24T00:20:00.0000000" actualValue="False" actualIsGood="true"
                      issue="ValueIssue" resultTimeStamp="2016-12-24T00:20:00.0000000"
                      resultExpectedValue="True" resultActualValue="False" resultExpectedIsGood="true"
                      resultActualIsGood="true" />
  <MeasurementCompare testcase="10-Is Good Mismatch" tolerance="0"
                      expectedTimestamp="2016-12-24T00:21:00.0000000" expectedValue="11" expectedIsGood="true"
                      actualTimestamp="2016-12-24T00:21:00.0000000" actualValue="11" actualIsGood="false"
                      issue="IsGoodIssue" resultTimeStamp="2016-12-24T00:21:00.0000000"
                      resultExpectedValue="11" resultActualValue="11" resultExpectedIsGood="true"
                      resultActualIsGood="false" />
  <MeasurementCompare testcase="11-Missing Actual" tolerance="0"
                      expectedTimestamp="2016-12-24T00:21:00.0000000" expectedValue="11" expectedIsGood="true"
                      issue="Missing" resultTimeStamp="2016-12-24T00:21:00.0000000"
                      resultExpectedValue="11" resultExpectedIsGood="true" />
  <MeasurementCompare testcase="12-Missing Expected" tolerance="0"
